spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    url: jdbc:p6spy:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/cntytz/web/dao/rdbms/repo/xml/*.xml
